#!/usr/bin/env python3
# Copyright (c) 2026 Jeff Liu.
# SPDX-License-Identifier: MIT
#
# Ported into yanshi-rl-lab 2026-08-02 from the predecessor stack
# (unitree-g1-locomotion, S3-实验2 tooling/s3e2-rough-scenes/gen_rough_scenes.py,
# MIT, same author). Every parameter and its derivation is carried over
# unchanged; what changed is where it lives and how it finds its output
# directory -- see "Why this lives here now" below.

"""Generate the rough-terrain gate scenes for a robot, from published parameters.

    python scripts/tools/gen_rough_scenes.py                    # unitree/g1/dof29
    python scripts/tools/gen_rough_scenes.py --robot unitree/g1/dof29

Writes ``scene_rough_{low,mid}.xml`` and their height-field binaries next to
the robot's other scene files, i.e. inside the fetched asset tree. Those
outputs are deliberately NOT committed (third-party asset trees never are);
this script is how they come back, and it is deterministic -- a frozen seed
and no tuned constants, so a regenerated scene is byte-identical to the one a
published gate number was measured on.

**Why this lives here now.** ``benchmark/gates/velocity-rough-straight-g1.yaml``
is a committed, public exam whose two gates name these scene files. Until this
port, the only generator for them lived in a different repository, so a clone
of yanshi-rl-lab could not run its own rough exam -- and that repository is on
its way to being archived. An exam and the terrain it is measured on have to
ship together.

⚠️ Regenerating with different constants silently invalidates every number
measured on the old terrain. That is not hypothetical: the S3-实验2 card
records a low-band displacement of 9.72 m measured on a superseded sample; the
current terrain gives 7.09 m for the same policy (same ONNX, verified by md5).
The gate verdicts did not change, but the number did. If you change anything in
the PARAMETERS block, re-judge every affected result and say so in the ledger.
"""

from __future__ import annotations

import argparse
import sys
from pathlib import Path

import numpy as np

_REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(_REPO / "source" / "yanshi_rl_lab"))

DEFAULT_ROBOT = "unitree/g1/dof29"

# ── PARAMETERS (every value has a source; nothing is tuned) ─────────────────
# Terrain recipe: the predecessor stack's S3E1_ROUGH_NOSTAIRS_CFG, i.e. the
# official Isaac Lab ROUGH_TERRAINS_CFG with the two stair sub-terrains removed
# and the remaining proportions renormalized. Of that mix only the random-rough
# sub-terrain is mapped to this height field.
NOISE_LO, NOISE_HI = 0.02, 0.10  # official HfRandomUniformTerrainCfg.noise_range [m]
GRID_M = 0.1  # Isaac generator-head horizontal_scale [m]
SEED = 42  # frozen; the S3E2 evaluation seed convention
PATCH_X_M, PATCH_Y_M = 40.0, 12.0  # 20 s at the training envelope vx<=1.0, plus margin
GEOM_CENTER_X_M = 5.0  # patch centre; leaves 15 m behind the spawn point
HFIELD_BASE_Z_M = 0.1  # skirt depth below the field (stops fast contacts punching through)
GEOM_Z_OFFSET_M = 0.002  # 2 mm lift, avoids coplanar contact with the infinite plane

# Difficulty -> amplitude. Isaac's own random_uniform_terrain IGNORES difficulty
# (isaaclab terrains/height_field/hf_terrains.py says so in its docstring:
# constant 2-10 cm bumps at every row). The standard difficulty law of the other
# sub-terrains in the same mix is linear interpolation p(d) = lo + d*(hi - lo)
# (random_grid_terrain in trimesh/mesh_terrains.py; pyramid_sloped_terrain in
# hf_terrains.py). This applies THAT law to the official noise_range envelope,
# evaluated at each difficulty band's midpoint.
BANDS = {
    "low": (0.1, "(0.0, 0.2)"),
    "mid": (0.5, "(0.4, 0.6)"),
}


def amplitude(difficulty: float) -> float:
    return NOISE_LO + difficulty * (NOISE_HI - NOISE_LO)


SCENE_TEMPLATE = """<mujoco model="{model} rough-{band} scene">
  <!--
    GENERATED by scripts/tools/gen_rough_scenes.py -- do not edit by hand.
    Rough-terrain gate scene for {robot_key}, difficulty band {band_label}.

    Base scene: {base_scene} in this directory. Only the floor changes:
    infinite plane + one height-field patch on top.

    PARAMETER PROVENANCE (every number has a source; nothing tuned):
    - Terrain recipe = S3E1_ROUGH_NOSTAIRS_CFG: the official Isaac Lab
      ROUGH_TERRAINS_CFG with the two stair sub-terrains removed and the
      remaining proportions renormalized. Of that mix only the random-rough
      sub-terrain (official HfRandomUniformTerrainCfg: noise_range=(0.02,
      0.10) m, noise_step=0.02 m) is mapped to this hfield; grid pitch 0.1 m
      = the shared generator-head horizontal_scale.
    - Difficulty -> amplitude: Isaac's random_uniform_terrain ignores
      difficulty; the standard linear law p(d) = lo + d*(hi - lo) used by the
      other sub-terrains in the same mix is applied to the official
      noise_range envelope at the band midpoint:
          band {band_label}, midpoint d = {d:.2f}
          A = 0.02 + {d:.2f} * (0.10 - 0.02) = {amp:.3f} m
    - Realization: iid uniform heights in [0, A] on a 0.1 m grid, one frozen
      base sample (seed {seed}) shared by both bands -- the two scenes differ
      ONLY in amplitude, so difficulty is a single variable. MuJoCo
      interpolates bilinearly between nodes; Isaac uses spline upsampling to
      the same 0.1 m grid plus 5 mm vertical quantization.

    HONEST NON-EQUIVALENCE NOTE (required reading):
    This MJCF terrain is NOT bit-equivalent to the Isaac rough_nostairs
    terrain: only the random-rough sub-terrain is represented (boxes and
    pyramid slopes are not), the sampling/interpolation differ, and Isaac's
    random-rough amplitude is difficulty-independent while this scene uses
    the linear band law above. Gate-line legitimacy therefore comes from
    absolute physical bars + positive-control anchoring, NOT from terrain
    identity.
  -->
  <include file="{model_file}"/>

  <statistic center="0 0 0.5" extent="2.0"/>

  <visual>
    <headlight diffuse="0.6 0.6 0.6" ambient="0.3 0.3 0.3" specular="0 0 0"/>
    <rgba haze="0.15 0.25 0.35 1"/>
    <global azimuth="-130" elevation="-20"/>
  </visual>

  <asset>
    <texture type="skybox" builtin="gradient" rgb1="0.3 0.5 0.7" rgb2="0 0 0" width="512" height="3072"/>
    <texture type="2d" name="groundplane" builtin="checker" mark="edge" rgb1="0.2 0.3 0.4" rgb2="0.1 0.2 0.3"
      markrgb="0.8 0.8 0.8" width="300" height="300"/>
    <material name="groundplane" texture="groundplane" texuniform="true" texrepeat="5 5" reflectance="0.2"/>
    <!-- hfield_rough_{band}.bin: MuJoCo custom binary (int32 nrow,ncol + float32 data,
         values normalized to [0,1], actual max height = {hmax:.4f} m below in size[2]).
         nrow={nrow} x ncol={ncol} nodes at 0.1 m pitch = {patch_x:.1f} m x {patch_y:.1f} m patch.
         The "../" prefix is because the included model pins meshdir="meshes" and MuJoCo
         resolves hfield files through it; the file itself sits next to this scene. -->
    <hfield name="rough_{band}" file="../hfield_rough_{band}.bin" nrow="{nrow}" ncol="{ncol}"
      size="{hx:.1f} {hy:.1f} {hmax:.4f} {base_z:.1f}"/>
  </asset>

  <worldbody>
    <light pos="0 0 1.5" dir="0 0 -1" directional="true"/>
    <geom name="floor" size="0 0 0.05" type="plane" material="groundplane"/>
    <!-- patch spans x in [{xmin:.1f}, {xmax:.1f}], y in [-{hy:.1f}, +{hy:.1f}]; the +2 mm z offset
         avoids coplanar contact with the infinite plane (which stays as the
         safety net outside the patch). Friction/solver attributes are the
         MuJoCo defaults, identical to the flat scene's plane. -->
    <geom name="rough_terrain" type="hfield" hfield="rough_{band}" pos="{cx:.1f} 0 {zoff:.3f}"/>
  </worldbody>
</mujoco>
"""


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--robot", default=DEFAULT_ROBOT, help=f"robot key (default: {DEFAULT_ROBOT})")
    ap.add_argument("--out-dir", type=Path, default=None, help="override the output directory")
    args = ap.parse_args()

    from yanshi_rl_lab.robots import registry

    profile = registry.get(args.robot)
    # Output goes next to the robot's own scenes, located through the profile.
    # No path is written down here, and no other repository is referenced.
    base_scene = profile.asset_path("scene_mjcf")
    out_dir = args.out_dir or base_scene.parent
    out_dir.mkdir(parents=True, exist_ok=True)
    model_file = Path(profile.mjcf).name

    nrow = int(round(PATCH_X_M / GRID_M)) + 1
    ncol = int(round(PATCH_Y_M / GRID_M)) + 1
    rng = np.random.default_rng(SEED)
    base = rng.uniform(0.0, 1.0, size=(nrow, ncol)).astype(np.float32)  # shared base sample

    for band, (difficulty, band_label) in BANDS.items():
        amp = amplitude(difficulty)
        heights = base * amp
        hmax = float(heights.max())
        # MuJoCo renormalizes by the data maximum, so normalize here first and
        # carry the true maximum in the hfield size attribute.
        data = (heights / hmax).astype(np.float32)
        bin_path = out_dir / f"hfield_rough_{band}.bin"
        with open(bin_path, "wb") as handle:
            np.array([nrow, ncol], dtype=np.int32).tofile(handle)
            data.tofile(handle)

        xml_path = out_dir / f"scene_rough_{band}.xml"
        xml_path.write_text(
            SCENE_TEMPLATE.format(
                model=Path(profile.mjcf).stem,
                model_file=model_file,
                base_scene=base_scene.name,
                robot_key=profile.key,
                band=band,
                band_label=band_label,
                d=difficulty,
                amp=amp,
                seed=SEED,
                hmax=hmax,
                nrow=nrow,
                ncol=ncol,
                hx=PATCH_X_M / 2,
                hy=PATCH_Y_M / 2,
                base_z=HFIELD_BASE_Z_M,
                patch_x=PATCH_X_M,
                patch_y=PATCH_Y_M,
                xmin=GEOM_CENTER_X_M - PATCH_X_M / 2,
                xmax=GEOM_CENTER_X_M + PATCH_X_M / 2,
                cx=GEOM_CENTER_X_M,
                zoff=GEOM_Z_OFFSET_M,
            ),
            encoding="utf-8",
        )
        print(f"{band}: d={difficulty} A={amp:.3f} m  hmax={hmax:.4f} m  -> {xml_path.name}, {bin_path.name}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
