#!/usr/bin/env python3
# Copyright (c) 2026 Jeff Liu.
# SPDX-License-Identifier: MIT

"""Scaffold a new robot: ``python scripts/tools/new_robot.py <vendor> <model> <variant>``.

One command creates every file a new robot needs, each filled with TODO
placeholders and pointers to a worked example (the AgiBot X2 files, which were
built from scratch against vendor assets and document their provenance line by
line):

- ``source/yanshi_rl_lab/yanshi_rl_lab/robots/<vendor>/<model>/<variant>/{__init__.py, profile.py}``
- ``source/.../tasks/locomotion/velocity/config/<vendor>/<model>/<variant>/__init__.py``
- ``tests/test_<model>_<variant>_profile.py``

Missing vendor- and model-level ``__init__.py`` files are created too, so a
second variant of an existing model adds one directory and touches nothing
shared. Existing variant files are NEVER overwritten: the script refuses and
exits non-zero.

The ``<variant>`` segment is mandatory. It is upstream's own name for the
configuration (``dof29`` for a model published as ``g1_29dof``, ``v1_4_0`` for
a directory named ``X2_URDF-v1.4.0``) -- never invented here -- and it must
start with a letter because it is also a Python package name.

Design notes (why the scaffold looks the way it does):

- The generated ``profile.py`` starts with a module-level ``raise`` so that a
  half-filled profile can never be imported silently. Every value is a ``TODO``
  sentinel, never a plausible-looking number -- inventing robot facts is banned
  in this repository.
- The generated task registration is commented out: ``yanshi_rl_lab.tasks``
  imports every config package on startup, so a live registration call against
  an unfinished profile would take down every task in the framework.
- The generated test module skips itself while the profile scaffold is
  unfilled, keeping the suite green right after scaffolding.
"""

from __future__ import annotations

import argparse
import datetime
import re
import sys
from pathlib import Path

# Identity-segment naming rule shared with tasks/registry.py and
# robots/profile.py: lowercase with underscores, starting with a letter
# ("unitree", "g1", "dof29"). The registry derives class names and task IDs
# from these tokens; a leading digit would not be an importable package name.
NAME_RE = re.compile(r"^[a-z][a-z0-9_]*$")

_REPO_ROOT = Path(__file__).resolve().parents[2]

_HEADER = """\
# Copyright (c) {year} Jeff Liu.
# SPDX-License-Identifier: MIT
"""

_ROBOT_VENDOR_INIT = '''\
{header}
"""Robot profiles from vendor: {vendor}."""
'''

_ROBOT_MODEL_INIT = '''\
{header}
"""{vendor_title} {model}, one sub-package per configuration the vendor ships.

Variant names are upstream's own name for the configuration -- never invented
here (e.g. "dof29"/"dof23" for a model published as g1_29dof/g1_23dof).
Variants of one model share a single fetched asset tree, ``assets/{vendor}/{model}/``.
"""
'''

_ROBOT_VARIANT_INIT = '''\
{header}
"""{vendor_title} {model} ({variant} configuration), generated by scripts/tools/new_robot.py, {date}.

This package stays pure Python (no Isaac Lab imports): tests, asset tooling
and the MuJoCo deployment side all read profiles without a GPU stack present.
"""

# TODO(new_robot.py): once profile.py is filled in, re-enable this re-export
# (the profile scaffold raises on import until every TODO is resolved):
# from .profile import {profile_name}  # noqa: F401
'''

_ROBOT_PROFILE = '''\
{header}
"""{vendor_title} {model} profile -- SCAFFOLD, generated by scripts/tools/new_robot.py ({date}).

Follow the worked example ``robots/agibot/x2/v1_4_0/profile.py`` (a profile built
from scratch against vendor assets) and ``robots/unitree/g1/dof29/profile.py`` (a
profile migrated from a battle-tested stack). Non-negotiable rules:

- Every value must come from a verifiable source (vendor MJCF/URDF, official
  training config, or a documented physical derivation). Record the source in
  a comment next to the value, the way the X2/G1 profiles do.
- Derived (non-official) values -- e.g. PD gains obtained via the natural-
  frequency method when the vendor publishes none -- must say so explicitly.
- Register the vendor assets in ``assets/registry.py`` (pinned upstream
  commit + license label) and fetch them with ``python assets/fetch.py
  {vendor}/{model}`` BEFORE filling in the asset paths below.
"""

# Guard: an unfinished profile must never import silently (it sits above the
# imports so it fires even in environments without the package on the path).
# Delete this raise ONLY after every TODO sentinel below has been replaced
# with a sourced value.
raise NotImplementedError(
    "robots/{vendor}/{model}/{variant}/profile.py is an unfilled scaffold "
    "(generated by scripts/tools/new_robot.py). Replace every TODO below with "
    "verified vendor facts, then delete this raise."
)

from yanshi_rl_lab.robots.profile import ActuatorGroup, RobotProfile  # noqa: E402

# Sentinel used for every not-yet-researched value. If the raise above is
# removed while any sentinel is left, RobotProfile validation rejects the
# profile loudly (e.g. pd_mode="TODO" is not a legal mode).
TODO = "TODO"

{profile_name} = RobotProfile(
    vendor="{vendor}",
    model="{model}",
    # Upstream's own name for this configuration -- never invent one.
    variant="{variant}",
    # -- asset locations (relative to assets_root(); register + fetch first) --
    urdf=TODO,  # e.g. "unitree/g1/urdf/g1_description/g1_29dof_rev_1_0.urdf"
    mjcf=TODO,  # paired MJCF -- URDF and MJCF MUST come from the same source
    scene_mjcf=TODO,  # MJCF scene with a floor, used by sim2sim; None if none ships
    usd=None,  # None = spawn from the URDF (official USD path if one ships)
    # -- embodiment -------------------------------------------------------
    spawn_height_m=TODO,  # initial root height; document the derivation (X2: foot-sole-to-root + clearance)
    default_joint_pos={{
        # TODO: joint-name regex -> initial angle [rad]. Source: vendor keyframe
        # or official training config. Joints omitted here default to 0.0.
    }},
    actuator_groups={{
        # TODO: one ActuatorGroup per motor class, like the X2/G1 profiles.
        # If the vendor publishes no kp/kd, derive them with the natural-
        # frequency method (see the X2 profile for the worked derivation) and
        # write "derived, not official" in the comment.
        # "MOTOR-CLASS": ActuatorGroup(
        #     joint_names_expr=[".*_hip_.*"],
        #     effort_limit=TODO,      # from vendor MJCF/URDF actuator block
        #     velocity_limit=TODO,
        #     stiffness=TODO,         # kp
        #     damping=TODO,           # kd
        #     armature=TODO,          # from vendor MJCF (or motor datasheet)
        # ),
    }},
    # Real-robot SDK joint ordering. If the vendor publishes no SDK joint
    # table, use the vendor's own documented order (e.g. the MJCF actuator
    # order) and mark it as derived, like the X2 profile does.
    joint_sdk_names=[
        TODO,
    ],
    pd_mode=TODO,  # "implicit" or "explicit" -- getting this wrong flips the robot; see robots/profile.py
    # -- semantic body map (task recipes reference ONLY these slots) -------
    base_link=TODO,  # torso/base body name (X2: heaviest body carrying the IMU)
    feet_bodies=TODO,  # body-name regex for the feet (check the MJCF contact geoms)
    undesired_contact_bodies=TODO,  # regex of bodies that must not touch ground
    leg_deviation_joints=[TODO],  # joints kept near default in the leg (e.g. hip roll/yaw)
    arm_deviation_joints=[TODO],  # arm joints kept near default ([] if the robot has no arms)
    waist_deviation_joints=[TODO],  # waist joints kept near default ([] if no waist)
    # -- task-derivable facts ---------------------------------------------
    # None means "this fact does not exist for this robot" (see the Berkeley
    # Humanoid Lite profile for a real case) -- never a lazy default.
    target_base_height_m=TODO,  # standing root height used by the base-height reward
    min_base_height_m=TODO,  # termination floor for the root height
    self_collisions=TODO,  # from the official training config (True unless the vendor disables it)
    action_scale=TODO,  # 0.25 is the upstream convention; keep unless evidence says otherwise
    root_joint_name=TODO,  # free-joint name in the vendor MJCF (needed by sim2sim)
)
'''

_CONFIG_VENDOR_INIT = '''\
{header}
"""Velocity-task registrations for vendor: {vendor}."""
'''

_CONFIG_MODEL_INIT = '''\
{header}
"""{vendor_title} {model} task overlays, one sub-package per configuration."""
'''

_CONFIG_VARIANT_INIT = '''\
{header}
"""{vendor_title} {model} ({variant}) velocity-task registration (scaffold, {date}).

Empty-overlay acceptance rule: a robot with a complete profile trains with
NOTHING here but the registration call. Overrides may be added only when
measurement proves them necessary, each with a documented reason (see the
G1 config package for a real, fully documented override).
"""

# TODO(new_robot.py): uncomment once
# robots/{vendor}/{model}/{variant}/profile.py is filled in. Until then the
# profile import would raise (the scaffold guards itself), and because
# ``yanshi_rl_lab.tasks`` imports every config package on startup, a live call
# here would take down ALL task registration.
#
# from yanshi_rl_lab.robots.{vendor}.{model}.{variant}.profile import {profile_name}
# from yanshi_rl_lab.tasks.registry import register_velocity
#
# register_velocity({profile_name}, __name__, terrains=("flat",))
'''

_TEST_MODULE = '''\
{header}
"""Pure-Python validation of the {vendor_title} {model} ({variant}) profile (scaffold, {date}).

Generated by scripts/tools/new_robot.py. Extend it the way
``tests/test_x2_v1_4_0_profile.py`` does: joint-table checks, actuator-group
coverage, semantic-slot sanity, and (where possible) cross-checks against
the vendor model files.
"""

from __future__ import annotations

import sys
import types
from pathlib import Path

import pytest

_PKG_DIR = Path(__file__).resolve().parents[1] / "source" / "yanshi_rl_lab" / "yanshi_rl_lab"

# Stub-package trick shared by all profile tests: the real package __init__
# imports Isaac Lab, so only the pure-Python profile modules are imported
# underneath a namespace stub.
if "yanshi_rl_lab" not in sys.modules:
    stub = types.ModuleType("yanshi_rl_lab")
    stub.__path__ = [str(_PKG_DIR)]
    sys.modules["yanshi_rl_lab"] = stub

try:
    from yanshi_rl_lab.robots.{vendor}.{model}.{variant}.profile import {profile_name}  # noqa: E402
except NotImplementedError:  # pragma: no cover - scaffold state
    pytest.skip(
        "robots/{vendor}/{model}/{variant}/profile.py is still an unfilled scaffold; "
        "fill in the profile (and its TODOs) to activate this test module",
        allow_module_level=True,
    )

from yanshi_rl_lab.robots.profile import PD_MODES  # noqa: E402

# TODO: set the verified actuated-joint count (count the vendor MJCF actuator
# block, like the X2 tests do), then flesh out the robot-specific tests below.
EXPECTED_DOF: int | None = None


def test_expected_dof_is_declared():
    assert EXPECTED_DOF is not None, (
        "TODO(new_robot.py): set EXPECTED_DOF to the verified actuated-joint "
        "count before trusting this test module"
    )


def test_sdk_joint_table():
    joints = {profile_name}.joint_sdk_names
    assert joints is not None and len(joints) == EXPECTED_DOF
    assert len(set(joints)) == len(joints), "duplicate joint names"


def test_pd_mode_is_legal():
    assert {profile_name}.pd_mode in PD_MODES


def test_asset_paths_are_relative():
    for field in ("urdf", "mjcf", "scene_mjcf", "usd"):
        value = getattr({profile_name}, field)
        if value is not None:
            assert not Path(value).is_absolute(), f"{{field}} must be assets-root relative"


# TODO: add the robot-specific checks that made the X2/BHL test modules
# worth having: every joint covered by exactly one actuator group, gains
# positive and within an order of magnitude of a same-size-class robot,
# semantic-slot regexes matching real joints, height facts self-consistent,
# and a MuJoCo cross-check against the vendor MJCF (importorskip("mujoco")).
'''


def _render(template: str, vendor: str, model: str, variant: str) -> str:
    year = datetime.date.today().year
    return template.format(
        header=_HEADER.format(year=year).rstrip("\n"),
        vendor=vendor,
        model=model,
        variant=variant,
        vendor_title=vendor.replace("_", " ").title(),
        profile_name=f"{model.upper()}_{variant.upper()}_PROFILE",
        test_stem=f"{model}_{variant}",
        date=datetime.date.today().isoformat(),
    )


def _plan_files(repo_root: Path, vendor: str, model: str, variant: str) -> dict[Path, str]:
    """Map of target path -> rendered content, variant-level files only."""
    pkg = repo_root / "source" / "yanshi_rl_lab" / "yanshi_rl_lab"
    robots = pkg / "robots" / vendor / model / variant
    config = pkg / "tasks" / "locomotion" / "velocity" / "config" / vendor / model / variant
    return {
        robots / "__init__.py": _render(_ROBOT_VARIANT_INIT, vendor, model, variant),
        robots / "profile.py": _render(_ROBOT_PROFILE, vendor, model, variant),
        config / "__init__.py": _render(_CONFIG_VARIANT_INIT, vendor, model, variant),
        repo_root / "tests" / f"test_{model}_{variant}_profile.py": _render(
            _TEST_MODULE, vendor, model, variant
        ),
    }


def _plan_parent_inits(repo_root: Path, vendor: str, model: str, variant: str) -> dict[Path, str]:
    """Vendor- and model-level ``__init__.py`` files, created only when missing.

    A second variant of an already-registered model therefore adds exactly one
    directory and touches nothing shared.
    """
    pkg = repo_root / "source" / "yanshi_rl_lab" / "yanshi_rl_lab"
    config = pkg / "tasks" / "locomotion" / "velocity" / "config"
    return {
        pkg / "robots" / vendor / "__init__.py": _render(_ROBOT_VENDOR_INIT, vendor, model, variant),
        pkg / "robots" / vendor / model / "__init__.py": _render(
            _ROBOT_MODEL_INIT, vendor, model, variant
        ),
        config / vendor / "__init__.py": _render(_CONFIG_VENDOR_INIT, vendor, model, variant),
        config / vendor / model / "__init__.py": _render(_CONFIG_MODEL_INIT, vendor, model, variant),
    }


def scaffold(repo_root: Path, vendor: str, model: str, variant: str) -> list[Path]:
    """Create all scaffold files; refuse to touch anything that exists."""
    for name, value in (("vendor", vendor), ("model", model), ("variant", variant)):
        if not NAME_RE.match(value):
            raise SystemExit(
                f"{name} {value!r} is invalid: use lowercase letters, digits and "
                "underscores, starting with a letter (e.g. 'unitree', 'humanoid_lite', "
                "'dof29'). A leading digit would not be an importable package name -- "
                "write 'dof29', not '29dof'."
            )

    files = _plan_files(repo_root, vendor, model, variant)
    existing = [p for p in files if p.exists()]
    if existing:
        listing = "\n  ".join(str(p.relative_to(repo_root)) for p in existing)
        raise SystemExit(
            f"Refusing to overwrite existing files for {vendor}/{model}/{variant}:\n  {listing}\n"
            "Delete them yourself first if you really mean to re-scaffold."
        )

    created: list[Path] = []
    for path, content in _plan_parent_inits(repo_root, vendor, model, variant).items():
        if not path.exists():
            path.parent.mkdir(parents=True, exist_ok=True)
            path.write_text(content, encoding="utf-8")
            created.append(path)
    for path, content in files.items():
        path.parent.mkdir(parents=True, exist_ok=True)
        path.write_text(content, encoding="utf-8")
        created.append(path)
    return created


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    parser.add_argument("vendor", help="vendor name, lowercase_with_underscores (e.g. unitree)")
    parser.add_argument("model", help="model name, lowercase_with_underscores (e.g. g1, humanoid_lite)")
    parser.add_argument(
        "variant",
        help="configuration name, UPSTREAM'S OWN (e.g. dof29, v1_4_0, humanoid). "
        "Must start with a letter -- it is a package name, so write 'dof29', not '29dof'.",
    )
    parser.add_argument(
        "--repo-root",
        type=Path,
        default=_REPO_ROOT,
        help="repository root to scaffold into (default: this script's repo; overridable for tests)",
    )
    args = parser.parse_args()

    created = scaffold(args.repo_root.resolve(), args.vendor, args.model, args.variant)
    key = f"{args.vendor}/{args.model}/{args.variant}"
    print(f"Scaffolded robot {key}:")
    for path in created:
        print(f"  created  {path.relative_to(args.repo_root.resolve())}")
    print(
        "\nNext steps:\n"
        f"  1. Assets: if {args.vendor}/{args.model} is NOT yet in assets/registry.py, add it\n"
        f"     (pinned commit + license) and run: python assets/fetch.py {args.vendor}/{args.model}\n"
        "     If another variant of this model is already registered, the assets are\n"
        "     already fetched -- variants share one asset tree, do NOT add a second key.\n"
        f"  2. Fill in robots/{args.vendor}/{args.model}/{args.variant}/profile.py\n"
        "     (every TODO, with sources), then delete its guard raise.\n"
        "  3. Uncomment the registration call in the velocity config package.\n"
        f"  4. Flesh out tests/test_{args.model}_{args.variant}_profile.py and run pytest.\n"
        "  5. Add a gate file under benchmark/gates/ before the first training run\n"
        "     (pre-registration discipline: gates are frozen before the run they judge)."
    )
    return 0


if __name__ == "__main__":
    sys.exit(main())
