#!/usr/bin/env python3
# Copyright (c) 2026 Jeff Liu.
# SPDX-License-Identifier: MIT

"""Render ROBOTS_INTRO.md -- every robot configuration this framework carries.

    python scripts/tools/render_robots_intro.py            # write the file
    python scripts/tools/render_robots_intro.py --check    # CI: fail if stale

Generated rather than written by hand, and for one reason: a hand-maintained
status table is a second copy of facts that live in the code, and second
copies go stale silently. Everything below is read from the repository at
render time -- the robot registry, the pinned asset registry, the frozen gate
files, the leaderboard entries. Onboard a robot and this file grows a row; it
cannot claim a robot is tested when nothing tested it.

What "tested" is allowed to mean here is deliberately narrow. The tiers are
derived, never asserted:

    ranked        a leaderboard entry exists under benchmark/results/
    exam frozen   a gate file names this robot, but nothing has been ranked
    registered    a profile and task exist; no exam written yet

No tier means "it works". A ranked robot may well be ranked with failing
gates -- Berkeley Humanoid Lite is, on purpose, because a board that lists
only passes reports by omission.

Pure stdlib apart from the profile import (itself pure Python), so CI can run
--check with nothing installed.
"""

from __future__ import annotations

import argparse
import json
import sys
from pathlib import Path

_REPO = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(_REPO / "source" / "yanshi_rl_lab"))

OUTPUT = _REPO / "ROBOTS_INTRO.md"
GATES_DIR = _REPO / "benchmark" / "gates"
RESULTS_DIR = _REPO / "benchmark" / "results" / "v1"
THUMB_DIR = _REPO / "docs" / "media" / "robots"

BANNER = "<!-- Generated by scripts/tools/render_robots_intro.py -- do not edit by hand. -->"


def _gate_field(path: Path, key: str) -> str | None:
    """First top-level ``key: value`` in a gate file (no YAML dependency)."""
    for line in path.read_text(encoding="utf-8").splitlines():
        if line.startswith(f"{key}: "):
            return line[len(key) + 2 :].strip()
    return None


def collect_exams() -> dict[str, list[tuple[str, str]]]:
    """robot key -> [(exam, task)], sorted."""
    exams: dict[str, list[tuple[str, str]]] = {}
    if not GATES_DIR.is_dir():
        return exams
    for path in sorted(GATES_DIR.glob("*.yaml")):
        robot = _gate_field(path, "robot")
        task = _gate_field(path, "task")
        if robot and task:
            exams.setdefault(robot, []).append((path.stem, task))
    return exams


def collect_results() -> dict[str, list[dict]]:
    """robot key -> [result documents], sorted by exam then file name."""
    results: dict[str, list[dict]] = {}
    if not RESULTS_DIR.is_dir():
        return results
    for path in sorted(RESULTS_DIR.rglob("*.json")):
        data = json.loads(path.read_text(encoding="utf-8"))
        results.setdefault(data["robot"], []).append(data)
    for entries in results.values():
        entries.sort(key=lambda d: (d.get("exam", ""), d.get("date", "")))
    return results


def load_asset_registry() -> dict:
    """assets/registry.py ASSETS, imported without importing the package."""
    import importlib.util

    spec = importlib.util.spec_from_file_location("assets_registry", _REPO / "assets" / "registry.py")
    module = importlib.util.module_from_spec(spec)
    spec.loader.exec_module(module)
    return module.ASSETS


def status_of(key: str, exams: dict, results: dict) -> str:
    if results.get(key):
        return "ranked"
    if exams.get(key):
        return "exam frozen"
    return "registered"


def _upstream_lines(entry: dict) -> list[str]:
    lines = []
    for source in entry["sources"]:
        repo = source["repo"].rstrip("/")
        commit = source["commit"]
        name = repo.rsplit("/", 1)[-1]
        lines.append(f"[{name}]({repo}/tree/{commit}) @ `{commit[:12]}`")
    return lines


def render(profiles: dict) -> str:
    exams = collect_exams()
    results = collect_results()
    assets = load_asset_registry()

    out = [
        BANNER,
        "",
        "# Robots",
        "",
        "Every robot configuration this framework carries, what it is pinned to, and",
        "how far it has actually been taken here. Identity is",
        "`<vendor>/<model>/<variant>`; the variant segment is mandatory, so a row",
        "always says *which* configuration of a model it means.",
        "",
        "| Status | Meaning |",
        "|---|---|",
        "| **ranked** | a leaderboard entry exists — see [Yanshi Rank](benchmark/site/rank.md) |",
        "| **exam frozen** | acceptance gates are written and frozen; nothing ranked yet |",
        "| **registered** | profile and task exist; no exam written yet |",
        "",
        "None of these means \"it works\". A ranked robot can be ranked with failing",
        "gates, and one below is — a board that lists only passes reports by omission.",
        "",
        "Robot models are **not** redistributed here. Each is fetched from a pinned",
        "upstream commit and stays under its vendor's licence; the thumbnails are",
        "renders of those models, made by",
        "`scripts/tools/render_robot_thumbs.py`.",
        "",
        "## At a glance",
        "",
        "| | Robot | DoF | Status | Upstream licence |",
        "|---|---|---|---|---|",
    ]
    for key in sorted(profiles):
        profile = profiles[key]
        thumb = THUMB_DIR / f"{key.replace('/', '-')}.png"
        rel = thumb.relative_to(_REPO).as_posix()
        cell = f'<img src="{rel}" width="96" alt="{key}">' if thumb.is_file() else "—"
        dof = len(profile.joint_sdk_names) if profile.joint_sdk_names else "?"
        licence = assets.get(profile.asset_key, {}).get("license", "—")
        out.append(
            f"| {cell} | `{key}` | {dof} | {status_of(key, exams, results)} | {licence} |"
        )
    out.append("")

    for key in sorted(profiles):
        profile = profiles[key]
        entry = assets.get(profile.asset_key)
        out += [f"## `{key}`", ""]
        out += [
            f"- **Configuration**: {profile.variant} — {len(profile.joint_sdk_names or [])} actuated joints",
            f"- **Assets**: `{profile.asset_key}` (shared by every variant of this model), "
            f"licence {entry['license'] if entry else '—'}",
        ]
        if entry:
            for line in _upstream_lines(entry):
                out.append(f"  - {line}")
        out.append(f"- **Status**: {status_of(key, exams, results)}")

        robot_exams = exams.get(key, [])
        if robot_exams:
            listed = ", ".join(
                f"[`{exam}`](benchmark/gates/{exam}.yaml) ({task})" for exam, task in robot_exams
            )
            out.append(f"- **Exams**: {listed}")
        else:
            out.append("- **Exams**: none written yet")

        for result in results.get(key, []):
            metrics = ", ".join(
                f"{name} {next(iter(per_seed.values()))}" for name, per_seed in result["metrics"].items()
            )
            out.append(
                f"- **Ranked** on `{result['exam']}` ({len(result['seeds'])} seed): {metrics}"
            )
        out.append("")

    out += [
        "## Adding one",
        "",
        "```bash",
        "python scripts/tools/new_robot.py <vendor> <model> <variant>",
        "```",
        "",
        "The variant is upstream's own name for the configuration — `dof29` because",
        "Unitree ships `g1_29dof_rev_1_0.urdf`, `v1_4_0` because the X2 model",
        "directory is `X2_URDF-v1.4.0` — and it must start with a letter, because",
        "every segment is also a Python package name. See `AGENTS.md` for the rules",
        "and `yanshi robots` for what is registered right now.",
        "",
    ]
    return "\n".join(out)


def main() -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="fail if the file on disk is stale")
    args = ap.parse_args()

    from yanshi_rl_lab.robots import registry

    text = render(registry.all_profiles())

    if args.check:
        if not OUTPUT.is_file():
            print(f"{OUTPUT.name} is missing; run scripts/tools/render_robots_intro.py", file=sys.stderr)
            return 1
        if OUTPUT.read_text(encoding="utf-8") != text:
            print(
                f"{OUTPUT.name} is stale (a robot, exam or leaderboard entry changed). "
                "Re-run scripts/tools/render_robots_intro.py and commit the result.",
                file=sys.stderr,
            )
            return 1
        print(f"{OUTPUT.name} is up to date")
        return 0

    OUTPUT.write_text(text, encoding="utf-8")
    missing = [
        key
        for key in registry.keys()
        if not (THUMB_DIR / f"{key.replace('/', '-')}.png").is_file()
    ]
    print(f"wrote {OUTPUT.relative_to(_REPO)}")
    if missing:
        print(
            f"note: no thumbnail for {missing} -- run scripts/tools/render_robot_thumbs.py",
            file=sys.stderr,
        )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
